spring.config.import=classpath:database.properties

#Pour l'acces aux images depuis le classpath
spring.web.resources.static-locations=classpath:/image/

#Pour l'acces aux image depuis un repertoir externe
memory.card.front.path=@memory.card.front.path@
memory.card.back.path=@memory.card.front.path@

api.version.path=@api.version.path@

#Cors
cors.domains=@cors.domains@