spring.datasource.platform: org.postgresql.Driver
spring.datasource.driver-class-name: org.postgresql.Driver
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url = ${DATABASE_URL_AET}
spring.datasource.username = ${DATABASE_USER_AET}
spring.datasource.password = ${DATABASE_PASSWORD_AET}
spring.jpa.properties.hibernate.default_schema: @database.schema@